### ISSUE TITLE
Design trip selector 6Hr

### ISSUE THREAD

**Issue by emily-yang** [project-aura/client#6]

**Comment by magicmitra** [comment]
Progress as off 2/28/12:28 PM : Filter works with aura and postal code as parameters.
TODO: add 3rd parameter 'purpose' of trip.

**Comment by magicmitra** [comment]
Progress as oof 2/28/01:30 PM : previous TODO has been finished. 'purpose' has been added as 3rd parameter to fetcher();
it is now: fetcher(postalCode, aura, purpose);

**Comment by magicmitra** [comment]
**Done for the purposes of this sprint.**
TODO: attach script to button, will be **for next sprint**.
